name: CommandAPI
main: dev.jorel.commandapi.CommandAPIMain
version: 3.0
description: An API to use Minecraft 1.13s new command UI
author: Skepter
website: https://www.jorel.dev/1.13-Command-API/
softdepend: [NBTAPI]