name: CommandAPI
main: dev.jorel.commandapi.CommandAPIMain
bootstrapper: dev.jorel.commandapi.CommandAPIBootstrap
version: ${version}
description: An API to use Minecraft 1.13s new command UI
authors:
  - Skepter
  - Will Kroboth
  - DerEchtePilz
website: https://www.jorel.dev/CommandAPI/
softdepend:
  - NBTAPI
provides:
    - CommandAPINetworking
api-version: '1.20.6'
folia-supported: true
