# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [push]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          17,    # Current Java LTS & minimum supported by Minecraft
        ]
        # and run on both Linux and Windows
        # os: [ubuntu-20.04, windows-2022]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven
      - name: build CommandAPI using maven
        run: mvn clean install --batch-mode -PPlatform.Bukkit
      - name: CommandAPI plugin artifact
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v2
        with:
          name: CommandAPI (plugin)
          path: |
            commandapi-plugin/target/CommandAPI*.jar
            !commandapi-plugin/target/*sources.jar
            !commandapi-plugin/target/*javadoc.jar
      - name: CommandAPI core artifact
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v2
        with:
          name: CommandAPI (core)
          path: |
            commandapi-core/target/CommandAPI*.jar
            !commandapi-core/target/*sources.jar
            !commandapi-core/target/*javadoc.jar
      - name: CommandAPI shade artifact
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v2
        with:
          name: CommandAPI (shade)
          path: |
            commandapi-shade/target/CommandAPI*.jar
            !commandapi-shade/target/*sources.jar
            !commandapi-shade/target/*javadoc.jar
      - name: build CommandAPI examples in examples/
        run: cd ./examples; ./build.sh;
